version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3005:3005"
    networks:
      - app-network
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
    depends_on:
      - db
    network_mode: bridge

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - app-network
    network_mode: bridge

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app-network
    network_mode: bridge

networks:
  app-network:
    
